import type {
  AuditEntry,
  Building,
  Location,
  Pathway,
  RouteNode,
  UserAccount,
} from "../types";

export const campusCenter: [number, number] = [16.720868, 121.689698];
export const buildings: Building[] = [
  {
    id: "ccsict",
    name: "CCSICT Building",
    code: "BLD-SCI-01",
    points: [
      [16.72117, 121.68908],
      [16.72117, 121.68945],
      [16.72088, 121.68947],
      [16.72087, 121.68909],
    ],
  },
  {
    id: "library",
    name: "University Library",
    code: "LIB-001",
    points: [
      [16.72112, 121.69005],
      [16.72112, 121.69038],
      [16.72084, 121.69039],
      [16.72084, 121.69006],
    ],
  },
  {
    id: "science",
    name: "Science Hall",
    code: "SCI-002",
    points: [
      [16.72045, 121.68884],
      [16.72047, 121.68919],
      [16.72018, 121.6892],
      [16.72017, 121.68886],
    ],
  },
  {
    id: "student",
    name: "Student Center",
    code: "STU-CTR-01",
    points: [
      [16.72036, 121.69003],
      [16.72036, 121.69035],
      [16.72011, 121.69035],
      [16.72011, 121.69004],
    ],
  },
  {
    id: "engineering",
    name: "Engineering Building",
    code: "ENG-001",
    points: [
      [16.72172, 121.68952],
      [16.72172, 121.6899],
      [16.72143, 121.68991],
      [16.72143, 121.68953],
    ],
  },
];
export const locations: Location[] = [
  {
    id: "bldg-ccsict",
    name: "CCSICT Building",
    code: "BLD-SCI-01",
    type: "Building",
    parentId: null,
    function: "Academic building",
    keywords: "computer science, IT",
    status: "Active",
    lat: 16.72102,
    lng: 121.68929,
    positioned: true,
  },
  {
    id: "flr-ccsict-2",
    name: "Floor 2",
    code: "FLR-CCSICT-02",
    type: "Floor",
    parentId: "bldg-ccsict",
    function: "Academic floor",
    keywords: "classrooms, labs",
    status: "Active",
    lat: 16.72102,
    lng: 121.68929,
    positioned: true,
  },
  {
    id: "lab1",
    name: "Computer Lab 1",
    code: "LAB-CCSICT-201",
    type: "Laboratory",
    parentId: "flr-ccsict-2",
    building: "CCSICT Building",
    floor: "2nd Floor",
    function: "Programming and computer-based activities",
    keywords: "programming, coding, lab",
    status: "Active",
    lat: 16.72102,
    lng: 121.68929,
    positioned: true,
  },
  {
    id: "room1",
    name: "Room 1",
    code: "R-CCSICT-202",
    type: "Room",
    parentId: "flr-ccsict-2",
    building: "CCSICT Building",
    floor: "2nd Floor",
    function: "General room",
    keywords: "room, lecture, activity",
    status: "Active",
    lat: 16.72105,
    lng: 121.68932,
    positioned: true,
  },
  {
    id: "faculty-office",
    name: "Faculty Office",
    code: "OFF-CCSICT-203",
    type: "Office",
    parentId: "flr-ccsict-2",
    building: "CCSICT Building",
    floor: "2nd Floor",
    function: "Faculty consultation",
    keywords: "faculty, consultation, office",
    status: "Active",
    lat: 16.72095,
    lng: 121.6892,
    positioned: true,
  },
  {
    id: "cr-floor-2",
    name: "CR Floor 2",
    code: "CR-CCSICT-204",
    type: "Restroom",
    parentId: "flr-ccsict-2",
    building: "CCSICT Building",
    floor: "2nd Floor",
    function: "Full restroom facility",
    keywords: "toilet, sink, comfort room",
    status: "Active",
    lat: 16.7209,
    lng: 121.68915,
    positioned: true,
  },
  {
    id: "bldg-library",
    name: "University Library",
    code: "LIB-001",
    type: "Facility",
    parentId: null,
    function: "Reading and research",
    keywords: "books, research, study",
    status: "Active",
    lat: 16.72098,
    lng: 121.69022,
    positioned: true,
  },
];
export const routeNodes: RouteNode[] = [
  {
    id: "ccsict-entry",
    name: "CCSICT Entrance",
    nodeType: "Entrance",
    associatedPlaceId: "ccsict",
    lat: 16.72088,
    lng: 121.68929,
  },
  {
    id: "junction-a",
    name: "Walkway Junction A",
    nodeType: "Junction",
    associatedPlaceId: null,
    lat: 16.72068,
    lng: 121.6897,
  },
  {
    id: "library-entry",
    name: "Library Entrance",
    nodeType: "Entrance",
    associatedPlaceId: "library",
    lat: 16.72084,
    lng: 121.6902,
  },
  {
    id: "student-entry",
    name: "Student Center Entrance",
    nodeType: "Entrance",
    associatedPlaceId: "student",
    lat: 16.72036,
    lng: 121.69003,
  },
  {
    id: "engineering-entry",
    name: "Engineering Entrance",
    nodeType: "Entrance",
    associatedPlaceId: "engineering",
    lat: 16.72143,
    lng: 121.68972,
  },
];
export const pathways: Pathway[] = [
  {
    id: "ccsict-junction",
    name: "CCSICT Entrance → Walkway Junction A",
    sourceNodeId: "ccsict-entry",
    destinationNodeId: "junction-a",
    distance: "48 m",
    time: "1 min",
    shade: "Mostly Shaded",
    type: "Campus walkway",
    direction: "Two-way",
    status: "Open",
    pathPoints: [[16.72074, 121.68948]],
  },
  {
    id: "junction-library",
    name: "Walkway Junction A → Library Entrance",
    sourceNodeId: "junction-a",
    destinationNodeId: "library-entry",
    distance: "56 m",
    time: "1 min",
    shade: "Partial Shade",
    type: "Campus walkway",
    direction: "Two-way",
    status: "Open",
    pathPoints: [[16.72075, 121.68995]],
  },
  {
    id: "junction-student",
    name: "Walkway Junction A → Student Center Entrance",
    sourceNodeId: "junction-a",
    destinationNodeId: "student-entry",
    distance: "42 m",
    time: "1 min",
    shade: "Fully Shaded",
    type: "Campus walkway",
    direction: "Two-way",
    status: "Open",
    pathPoints: [[16.72051, 121.68987]],
  },
];
export const users: UserAccount[] = [
  {
    id: "usr-1",
    username: "admin01",
    createdAt: "Aug 10, 2026 · 9:15 AM",
    lastSignIn: "Aug 17, 2026 · 10:42 PM",
    role: "Administrator",
  },
  {
    id: "usr-2",
    username: "staff02",
    createdAt: "Aug 12, 2026 · 1:30 PM",
    lastSignIn: "Aug 17, 2026 · 8:16 PM",
    role: "Staff",
  },
  {
    id: "usr-3",
    username: "user03",
    createdAt: "Aug 15, 2026 · 11:05 AM",
    lastSignIn: null,
    role: "User",
  },
];
export const auditEntries: AuditEntry[] = [
  {
    id: "a1",
    actor: "admin01",
    action: "Updated Location",
    target: "Computer Lab 1",
    createdAt: "Aug 17, 2026 · 2:05 PM",
    category: "Admin",
    detail: "Floor plan updated for level 2.",
  },
  {
    id: "a2",
    actor: "admin01",
    action: "Moved Route Node",
    target: "CAS Entrance",
    createdAt: "Aug 17, 2026 · 1:52 PM",
    category: "Admin",
  },
  {
    id: "a3",
    actor: "student01",
    action: "Searched Location",
    target: "CAS ROOM 101",
    createdAt: "Aug 17, 2026 · 1:30 PM",
    category: "User",
  },
  {
    id: "a4",
    actor: "student02",
    action: "Requested Route",
    target: "CAS ROOM 101 → Computer Lab 1",
    createdAt: "Aug 17, 2026 · 1:22 PM",
    category: "User",
  },
  {
    id: "a5",
    actor: "staff02",
    action: "Removed User",
    target: "staff02",
    createdAt: "Aug 17, 2026 · 12:40 PM",
    category: "Admin",
  },
  ...Array.from({ length: 20 }, (_, index) => ({
    id: `a-seed-${index + 1}`,
    actor: "system",
    action: "Health Check",
    target: `Campus service ${index + 1}`,
    createdAt: `Aug ${16 - Math.floor(index / 5)}, 2026 · ${String(9 + (index % 10)).padStart(2, "0")}:00 AM`,
    category: "System" as const,
    detail: "Scheduled system activity recorded by the campus service.",
  })),
];
