BEGIN;

CREATE TABLE IF NOT EXISTS public.location_photo (
    photo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_type VARCHAR(8) NOT NULL CHECK (owner_type IN ('building', 'location')),
    owner_id BIGINT NOT NULL,
    position INTEGER NOT NULL CHECK (position >= 0),
    filename VARCHAR(255) NOT NULL,
    mime_type VARCHAR(32) NOT NULL,
    content BYTEA NOT NULL,
    is_cover BOOLEAN NOT NULL DEFAULT FALSE
);

-- Photos are served only by the admin Locations API. Supabase grants API roles
-- access to new public tables by default, so deny direct table access.
ALTER TABLE public.location_photo ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.location_photo
    FROM PUBLIC, anon, authenticated, service_role;

CREATE INDEX IF NOT EXISTS location_photo_owner_order
    ON public.location_photo (owner_type, owner_id, position);
CREATE UNIQUE INDEX IF NOT EXISTS location_photo_one_cover
    ON public.location_photo (owner_type, owner_id) WHERE is_cover;

INSERT INTO public.location_photo (owner_type, owner_id, position, filename, mime_type, content, is_cover)
SELECT 'building', building_id, 0, 'Existing location photo',
       COALESCE(photo_mime_type, 'application/octet-stream'), photo, TRUE
FROM public.building AS owner
WHERE photo IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM public.location_photo AS existing
                  WHERE existing.owner_type = 'building' AND existing.owner_id = owner.building_id);

INSERT INTO public.location_photo (owner_type, owner_id, position, filename, mime_type, content, is_cover)
SELECT 'location', location_id, 0, 'Existing location photo',
       COALESCE(photo_mime_type, 'application/octet-stream'), photo, TRUE
FROM public.location AS owner
WHERE photo IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM public.location_photo AS existing
                  WHERE existing.owner_type = 'location' AND existing.owner_id = owner.location_id);

COMMIT;
