import { useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { services } from '../../services/api'
import { Badge, Button, Card, Empty, Field, Modal, Pagination } from '../../components/UI'
import type { UserAccount } from '../../types'

export function Users() {
  const queryClient = useQueryClient(); const [query, setQuery] = useState(''); const [dialog, setDialog] = useState<'edit' | 'history' | 'remove' | null>(null); const [selected, setSelected] = useState<UserAccount | null>(null); const [username, setUsername] = useState(''); const [notice, setNotice] = useState(''); const { data } = useQuery({ queryKey: ['users', query], queryFn: () => services.users.list(query) })
  const close = () => setDialog(null); const openEdit = (user: UserAccount) => { setSelected(user); setUsername(user.username); setDialog('edit') }; const update = async () => { if (!selected) return; await services.users.update({ ...selected, username }); await queryClient.invalidateQueries({ queryKey: ['users'] }); await queryClient.invalidateQueries({ queryKey: ['logs'] }); close(); setNotice('User updated successfully.') }; const remove = async () => { if (!selected) return; await services.users.remove(selected.id); await queryClient.invalidateQueries({ queryKey: ['users'] }); await queryClient.invalidateQueries({ queryKey: ['logs'] }); close(); setNotice(`${selected.username} removed successfully.`) }
  return <div className="page"><div className="page-hero"><span className="page-icon">♙</span><div><h1>User Management</h1><p>Manage user accounts, sign-in metadata, and account-specific audit history.</p></div></div>{notice && <div className="notice" role="status">{notice}</div>}<Card className="search-card"><Field label="" placeholder="Search by username..." value={query} onChange={event => setQuery(event.target.value)} /><Button>＋ Add User</Button></Card><Card className="table-card"><div className="table-heading"><div><h2>Accounts</h2><p>Showing {data?.items.length ?? 0} users</p></div></div><div className="table-wrap"><table><thead><tr><th>USERNAME</th><th>CREATED AT</th><th>LAST SIGN IN</th><th>ROLE</th><th>ACTIONS</th></tr></thead><tbody>{(data?.items ?? []).map(user => <tr key={user.id}><td><strong>{user.username}</strong></td><td>{user.createdAt}</td><td>{user.lastSignIn ?? 'Never'}</td><td><Badge>{user.role}</Badge></td><td><button className="text-action" onClick={() => openEdit(user)}>Edit</button><button className="text-action" onClick={() => { setSelected(user); setDialog('history') }}>View History</button><button className="text-action danger-text" onClick={() => { setSelected(user); setDialog('remove') }}>Remove</button></td></tr>)}</tbody></table>{!data?.items.length && <Empty>No users found.</Empty>}</div><Pagination total={data?.total ?? 0} /></Card>{dialog === 'edit' && selected && <Modal title="Edit User" onClose={close}><Field label="USERNAME" value={username} onChange={event => setUsername(event.target.value)} /><p className="muted">Created {selected.createdAt}. Password values are never shown.</p><div className="modal-actions"><Button variant="subtle" onClick={close}>Cancel</Button><Button onClick={update}>Save Changes</Button></div></Modal>}{dialog === 'history' && selected && <Modal title="Audit History" onClose={close}><p className="muted">Account changes only. Password values are never shown.</p><div className="history-list"><div><small>Aug 16, 2026 · 4:35 PM</small><strong>Updated Username</strong><span>administrator01 → {selected.username}</span></div><div><small>Aug 14, 2026 · 11:20 AM</small><strong>Password Reset</strong></div><div><small>{selected.createdAt}</small><strong>Created User</strong></div></div><div className="modal-actions"><Button onClick={close}>Close</Button></div></Modal>}{dialog === 'remove' && selected && <Modal title="Remove User?" onClose={close}><p>This action will remove <strong>{selected.username}</strong>.</p><div className="modal-actions"><Button variant="subtle" onClick={close}>Cancel</Button><Button variant="danger" onClick={remove}>Remove User</Button></div></Modal>}</div>
}
