import { FormEvent, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from './AuthContext'
import { Button, Card, Field } from '../../components/UI'
import { services } from '../../services/api'
import mapIcon from '../../assets/figma/login/login-icon-3.svg'
import userIcon from '../../assets/figma/login/login-icon-4.svg'
import arrowIcon from '../../assets/figma/login/login-icon-5.svg'
export function Login() { const { login } = useAuth(); const navigate = useNavigate(); const [username,setUsername]=useState('admin_justine'); const [password,setPassword]=useState('password123'); const [show,setShow]=useState(false); const [error,setError]=useState(''); const submit=async(e:FormEvent)=>{e.preventDefault();setError('');try{await login(username,password);navigate('/dashboard')}catch(err){setError(err instanceof Error?err.message:'Unable to sign in.')}}; return <div className="auth-page"><div className="ambient"/><Card className="login-card"><div className="auth-brand"><div className="auth-mark"><img src={mapIcon} alt=""/></div><h1>ISU-CAMP</h1><p>Admin Login</p></div><form onSubmit={submit}><Field label="USERNAME" value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username"/><label className="field"><span>PASSWORD</span><div className="password"><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/><button type="button" onClick={()=>setShow(!show)} aria-label="Toggle password visibility">{show?'◉':'◌'}</button></div></label><div className="forgot"><Link to="/reset-password">Forgot password?</Link></div>{error&&<div className="error">{error}</div>}<Button type="submit">Login <img src={arrowIcon} alt=""/></Button></form><footer>Authorized Personnel Only · Echague Main Campus</footer></Card></div> }
export function PasswordReset() { const navigate=useNavigate(); const [step,setStep]=useState<'request'|'code'|'new'|'success'>('request'); const [email,setEmail]=useState('admin@isu.edu.ph'); const [code,setCode]=useState('000000'); const [password,setPassword]=useState('password123'); const [error,setError]=useState(''); const submit=async()=>{try{if(step==='request')setStep('code');else if(step==='code')setStep('new');else if(step==='new'){await services.auth.reset(code,password);setStep('success')}}catch(e){setError(e instanceof Error?e.message:'Unable to reset password')}}; return <div className="auth-page"><div className="ambient"/><Card className="login-card"><div className="auth-brand"><div className="auth-mark"><img src={mapIcon} alt=""/></div><h1>ISU-CAMP</h1><p>Admin Login</p></div>{step==='success'?<><h2>Password reset successful</h2><p className="muted">Your password has been updated. You can now sign in.</p><Button onClick={()=>navigate('/login')}>Return to Login</Button></>:<><h2>{step==='request'?'Reset your password':step==='code'?'Enter verification code':'Create new password'}</h2><p className="muted">{step==='request'?'We will send a six-digit code to your admin email.':step==='code'?'Enter the code from the email. Use 000000 in the demo.':'Choose a new password with at least 8 characters.'}</p>{step==='request'&&<Field label="ADMIN EMAIL" value={email} onChange={e=>setEmail(e.target.value)} type="email"/>}{step==='code'&&<Field label="VERIFICATION CODE" value={code} onChange={e=>setCode(e.target.value)} inputMode="numeric"/>}{step==='new'&&<Field label="NEW PASSWORD" value={password} onChange={e=>setPassword(e.target.value)} type="password"/>}{error&&<div className="error">{error}</div>}<Button onClick={submit}>{step==='request'?'Send Code':step==='code'?'Continue':'Save Password'} <span>→</span></Button><Link className="back-link" to="/login">Back to login</Link></>}</Card></div> }
